### ISSUE TITLE
Software Spezifikation (Web Frontend)

### ISSUE THREAD

**Issue by BTBlueTiger** [BTBlueTiger/projektmanagement#4]
Damit es für alle Personen in den anderen Teams ersichtlich wird, wie das Web Frontend funktioniert und jeder die Möglichkeit hat auszuhelfen oder ggf. zu wechseln, sollen alle Kenntnis darüber haben können, wie das Frontend aufgebaut ist und arbeitet.
Ebenfalls lassen sich nur so Anregung oder Kritik anderer Teams in Review 2 gut nachvollziehen.
Dafür ist eine kleines für diesen Bereich bestimmte Spezifikation notwendig.

Beispiele der Komponenten:
- GUI Mock Up für den Visuellen Part
- API Beschreibung für das verwendete System sowie der Sprache

**Comment by shakerrrr** [comment]
- faq: neue frage erstellen
- bewertungen: -> alle bewertungen anzeigen
- möglichkeit neue bwertung zu erstellen, mit workload und custom text

**Comment by shakerrrr** [comment]
react.js für frontend

**Comment by shakerrrr** [comment]
diese woche mockups überarbeiten

**Comment by shakerrrr** [comment]
faq modulspezifisch entfernen -> eine generelle faq seite
