### ISSUE TITLE
Software Spezifikation (Mobile Endgeräte Frontend)

### ISSUE THREAD

**Issue by BTBlueTiger** [BTBlueTiger/projektmanagement#5]
Damit es für alle Personen in den anderen Teams ersichtlich wird, wie das Mobile Frontend funktioniert und jeder die Möglichkeit hat auszuhelfen oder ggf. zu wechseln, sollen alle Kenntnis darüber haben können, wie das Frontend aufgebaut ist und arbeitet.
Ebenfalls lassen sich nur so Anregung oder Kritik anderer Teams in Review 2 gut nachvollziehen.
Dafür ist eine kleines für diesen Bereich bestimmte Spezifikation notwendig.

Beispiele der Komponenten:
- GUI Mock Up für den Visuellen Part
- API Beschreibung für das verwendete System sowie der Sprache

**Comment by Lulon27** [comment]
Ich habe eine [Wiki-Seite](https://github.com/BTBlueTiger/projektmanagement/wiki/Mobiles-Frontend-(Android-App)) für die App erstellt und ein paar Mockups hochgeladen. Bitte drüber gucken.

**Comment by BTBlueTiger** [comment]
Ich finde, das Wiki ist gelungen. 

Es lässt sich gut ableiten, welches Ziel erreicht werden soll und was dafür benötigt wird.
Ich schreibe noch einmal das heraus, was ich hier finde, einmal als essenzielle User Storys und einmal als Feature User Storys.
Aus den Features könnten auch eigene Meilensteine gemacht werden, eine Idee der Zusammenfassung für einen Meilenstein steht in den Klammern.

----

# Essenzielle User Storys 

----

### Wer? 
Benutzer
### Was?
Navigationsleiste.
### Warum?
Es soll einfach sein zwischen den zwei Haupt Bildschirmen hin und herzuwechseln.
### Akzeptanzkriterium:
Auf dem unteren Bildschirm kann ich zwei Knöpfe vorfinden. Ein Knopf namens ````FAQ```` und einer ```Module```.
Klicke ich auf einen der Knöpfe, öffnet sich das passende Fenster zum Knopf.
Die Knöpfe bleiben dort bestehen, auch wenn ich den Bildschirm wechsel.

----

### Wer? 
Benutzer
### Was?
Hauptseite der Module
### Warum?
Dies soll eine Übersicht über die Module liefern.
### Akzeptanzkriterium:
Ich finde die Module vor, die zur Auswahl stehen. 
Aus dem Namen und den eingefügten Leisten lassen sich die Moduleigenschaften ableiten sowie 
durch die kurzen prägnanten Beschreibungen ein erster Eindruck gewinnen.

----

### Wer? 
Hauptseite der FAQ
### Was?
Eine erste Übersicht der vorhandenen FAQ
### Warum?
Eine Übersicht aller vorhandenen Fragen
### Akzeptanzkriterium:
Alle Fragen werden nacheinander aufgeführt.
Der Grundaufbau:
    - Frage mit Überschrift Eigenschaft.
    - Antwort in normaler Textform


# Feature User Storys 

----

### Wer? (Thema)
Benutzer (FAQ)
### Was?
Es soll möglich sein neue Fragen zu erstellen
### Warum?
Die FAQ soll sich lebendig weiter entwickeln können
### Akzeptanzkriterium:
Klicke ich auf einen Button, der mir suggeriert, dass ich hier Fragen hinzufügen kann, komme ich auf ein Formular.
Dieses Formular kann ausgefüllt werden und sollte intuitiv sein.
Wird der Button zum Einreichen gedrückt, kann ein Admin diese Frage prüfen, ggf. modifizieren und hinzufügen.

----

### Wer? 
Benutzer(FAQ)
### Was?
Die Fragen sollen kategorisiert werden
### Warum?
Es wirkt aufgeräumter und gewünschtes ist schneller gefunden
### Akzeptanzkriterium:
Einzelne Fragen werden ihrer Kategorie zugeordnet.
Tippe ich auf eine Frage öffnen sich alle Fragen passend zu dem Thema.

----

### Wer? 
Benutzer(FAQ)
### Was?
Kategorien haben Sprung Befehle
### Warum?
Es erleichtert das Benutzen der App
### Akzeptanzkriterium:
Öffne ich einen Reiter für bspw. die Module stehen alle Fragen ohne Antwort mit einem Sprungbefehl.
Unterhalb dieser Fragen befinden sich alle Fragen mit Antwort. 
Klicke ich auf eine Frage, unter einem Reiter, springt die App zur passenden Frage mit Antwort.

----

### Wer? 
Benutzer(Module)
### Was?
Module bekommen eine eigene Seite
### Warum?
Es sollen mehr Informationen dargestellt werden, was aus Platzgründen auf der Hauptseite unpassend wäre.
### Akzeptanzkriterium:
Wird ein Modul in der Zusammenfassung angeklickt, wird eine Seite geöffnet, die mir Detailtreue Informationen anbietet. 
Diese Details beinhalten rudimentär folgendes:
    - Dozent
    - ETC Punkte
    - Kurze Zusammenfassung der Kernpunkte des Moduls
    
----

### Wer? 
Benutzer(Module-Detailerweiterungen)
### Was?
Module erhalten Zoom Daten
### Warum?
Zoom sind in der Zeit von Hybrid oder Fernlehre wichtige Eckdaten
### Akzeptanzkriterium:
Ich finde hier den Zoomlink, sowie eine Möglichkeit ein Kenncode hinzuzufügen für mein Profil hinzuzufügen.

----

### Wer? 
Benutzer(Module-Detailerweiterungen)
### Was?
Module erhalten erweiterte Informationen
### Warum?
Die Seite wird durch Daten wie Zeitraum oder Tag informativer
### Akzeptanzkriterium:
Auf der Hauptseite eines Moduls werden mir Informationen wie der Zeitraum und Vorlesungszeit ersichtlich.
Durch anklicken werden die Informationen etwas feiner granuliert dargestellt. Beispielsweise wann Praktikas stattfinden oder
wenn Termine ein Thema haben werden diese aufgelistet.

----

### Wer? 
Benutzer(Module-Bewertungen)
### Was?
Module erhalten Bewertungen
### Warum?
Zum einen wird es interaktiver, zum anderen ist es eine Besonderheit der Anwendung
### Akzeptanzkriterium:
Es finden sich Bewertungen zu den einzelnen Modulen. Diese bestehen aus Bewertungen wie der Einschätzungen welche Java
Kenntnisse mitgebracht werden sollten oder Mathematik.
Optional können auch Texte hinzugefügt werden, in der die Bewertung begründet wird.

----

### Wer? 
Benutzer(Module-Bewertungen)
### Was?
Bewertungen werden gewertet
### Warum?
Aus allen Bewertungen soll ein Durchschnitt errechnet werden 
### Akzeptanzkriterium:
Aus den abgegebenen Bewertungen lässt sich ein Durchschnitt berechnen. Dieser findet sich beispielsweise am Anfang der Bewertungen, sowie auf der zusammenfassenden Modulseite.

----
