### ISSUE TITLE
Software Spezifikation (Backend)

### ISSUE THREAD

**Issue by BTBlueTiger** [BTBlueTiger/projektmanagement#6]
Damit es für alle Personen in den anderen Teams ersichtlich wird, wie das Backend funktioniert und jeder die Möglichkeit hat auszuhelfen oder ggf. zu wechseln, sollen alle Kenntnis darüber haben können, wie das Backend aufgebaut ist und arbeitet.
Ebenfalls lassen sich nur so Anregung oder Kritik anderer Teams in Review 2 gut nachvollziehen.
Dafür ist eine kleines für diesen Bereich bestimmte Spezifikation notwendig.

Beispiele der Komponenten:
- ER Diagramm um die Datenbank verständlich zu machen 
- API Beschreibung für das verwendete System sowie der Sprache
    - Klärung der Frage auf welcher Weise das Frontend mit dem Backend kommunizieren kann

**Comment by KevFischer** [comment]
Erster Prototyp für das [ER-Diagramm](https://github.com/BTBlueTiger/projektmanagement/wiki/Datenmodell) (hab schon viele Fehler und Optimierungen erkannt, möchte aber Donnerstag erst bisschen etwas abklären um unnötige Arbeit zu vermeiden).

**Comment by KevFischer** [comment]
Datenmodell wurde auf die Mobile Frontend Mockups angepasst und die dazugehörige [Wiki-Seite](https://github.com/BTBlueTiger/projektmanagement/wiki/Datenmodell) wurde dementsprechend geupdatet.
